[package]
name = "runtime-io"
version = "0.1.0"
authors = ["Aten <jincxmain@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp-runtime-interface = { version = "2.0.0", default-features = false, path = "../../../primitives/runtime-interface" }

[features]
default = ["std"]
std = [
    "sp-runtime-interface/std"
]