[package]
name = "tmp-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }

sp-api = { version = "4.0.0-dev", default-features = false, path = "../../../primitives/api" }
sp-version = { version = "4.0.0-dev", default-features = false, path = "../../../primitives/version" }
sp-runtime = { version = "4.0.0-dev", default-features = false, path = "../../../primitives/runtime" }

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",

    "sp-api/std",
    "sp-version/std",
    "sp-runtime/std",
]
